FROM python:3

RUN pip install --no-cache-dir eyed3

# TODO: Eventually, we can use something like this to build a Docker image with gpm-utils ready to use!
# WORKDIR /usr/src/gpm-utils
#
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt
#
# COPY . .
#
# CMD [ "python", "./gpm-utils.py"]
